/*
Copyright IBM Corp. All Rights Reserved.

SPDX-License-Identifier: Apache-2.0
*/

#ifndef _GREP11_H_
#define _GREP11_H_ 1

#define CKR_VENDOR_DEFINED_GREP11        CKR_VENDOR_DEFINED + 0x40000
#define CKR_IBM_GREP11_NOT_AUTHENTICATED CKR_VENDOR_DEFINED_GREP11 + 0x01
#define CKR_IBM_GREP11_CANNOT_UNMARSHAL  CKR_VENDOR_DEFINED_GREP11 + 0x02
#define CKR_IBM_GREP11_CANNOT_MARSHAL    CKR_VENDOR_DEFINED_GREP11 + 0x03
#define CKR_IBM_GREP11_CONFLICT          CKR_VENDOR_DEFINED_GREP11 + 0x04
#define CKR_IBM_GREP11_DBINTERNAL        CKR_VENDOR_DEFINED_GREP11 + 0x05

#endif
